package com.javasampleapproach.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Note")
public class Note {

	private String id;
	private String userName;
	private String topic;
	private String content;
	private String createdAt;
	private String title;

	public Note() {
	}

	public Note(String id, String userName, String topic, String content, String createdAt, String title) {
		this.id = id;
		this.userName = userName;
		this.topic = topic;
		this.content = content;
		this.createdAt = createdAt;
		this.title = title;
	}
	public Note(String id,String content) {
		this.id=id;
		this.content=content;
	}
	public Note(String id) {
		this.id=id;
	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "UserName")
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@DynamoDBAttribute(attributeName = "Topic")
	public String getTopic() {
		return topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	@DynamoDBAttribute(attributeName = "Content")
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@DynamoDBAttribute(attributeName = "CreatedAt")
	public String getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	@DynamoDBAttribute(attributeName = "Title")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Override
	public String toString() {
		return String.format("Note[id=%s, userName='%s', topic='%s', content='%s', title='%s']", id, userName, topic, content, title);
	}

}